[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "replace-with-32-plus-random-bytes"
client_id = "replace-with-clerk-oauth-application-client-id"
client_secret = "replace-with-clerk-oauth-application-client-secret"
server_metadata_url = "replace-with-clerk-oauth-application-discovery-url"
client_kwargs = { "prompt" = "consent" }
